// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrmyejvilobctxpqahsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybXllanZpbG9iY3R4cHFhaHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDAzNTMsImV4cCI6MjA2MzY3NjM1M30.nVcenQ8H_80RAd7VTgfE29fusqEHVcSK7IaPOClWH_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);